export default [
  {
    id: 'raketa',
    name: 'Studio Raketa',
    period: '04.2016 - 02.2020',
    position: 'frontend developer',
    description: 'All projects below are builded with Raketa CMS',
    projects: [
      {
        id: '1wd',
        url: 'https://www.chaosgroup.com',
        image: '/static/images/chaos.jpg',
        clientName: 'Chaos Group',
      },
      {
        id: '2fs',
        url: 'https://smokini.bg',
        image: '/static/images/smokini.jpg',
        clientName: 'Smokini',
      },
      {
        id: '3hfg',
        url: 'https://touchawesome.com',
        image: '/static/images/touchawsome.jpg',
        clientName: 'Touchawesome',
      },
      {
        id: '4khjkh',
        url: 'https://smartcom.bg',
        image: '/static/images/smartcom.jpg',
        clientName: 'Smartcom',
      },
      {
        id: '5kjlj',
        url: 'https://konek.bg',
        image: '/static/images/konek.jpg',
        clientName: 'Konek',
      },
      {
        id: '6bfg',
        url: 'https://unikalni-podaraci.com',
        image: '/static/images/podaraci.jpg',
        clientName: 'Уникални Подаръци',
      },
      {
        id: '7er',
        url: 'https://differentina.com',
        image: '/static/images/differentina.jpg',
        clientName: 'Differentina',
      },
      {
        id: '8berb',
        url: 'https://copycom.bg/bg',
        image: '/static/images/copycom.jpg',
        clientName: 'Copycom',
      },
    ],
  },
  {
    id: 'netea',
    name: 'Netea',
    period: '10.2015 - 01.2016',
    position: 'frontend developer',
    description: '',
    projects: [
      {
        id: '1bdfbd',
        url: 'https://www.lecturio.com',
        image: '/static/images/lecturio.jpg',
        clientName: 'Lecturio',
      },
    ],
  },
  {
    id: 'avalith',
    name: 'Avalith',
    period: '05.2013 - 10.2015',
    position: 'frontend developer',
    description: '',
    projects: [
      {
        id: '1berbs',
        url: 'https://www.historypin.org',
        image: '/static/images/historypin.jpg',
        clientName: 'Historypin',
      },
      {
        id: '2bdfbdf',
        url: 'http://zagorkacompany.bg',
        image: '/static/images/zagorcacompany.jpg',
        clientName: 'Zagorka Company',
      },
    ],
  },
  {
    id: 'hiend',
    name: 'HiEnd Publishing',
    period: '08.2010 – 05.2013',
    position: 'graphic designer',
    description: '',
    projects: [],
  },
  {
    id: 'tema',
    name: '“Tema” magazine',
    period: '08.2008 – 08.2010',
    position: 'graphic designer',
    projects: [],
    description: '',
  },
  {
    id: 'lambadjiev',
    name: 'Lambadjiev Standart',
    period: '10.2007 – 08.2008',
    position: 'graphic designer',
    projects: [],
    description: '',
  },
];
