export default [
  { id: 'sad', name: 'CSS3' },
  { id: 'das', name: 'SASS' },
  { id: 'vff', name: 'HTML5' },
  { id: 'vdfb', name: 'Javascript' },
  { id: 'vdf', name: 'React' },
  { id: 'csd', name: 'Typescript' },
  { id: 'ntyny', name: 'React Native' },
  { id: 'sdvbs', name: 'Styled components' },
  { id: 'dsvvs', name: 'Nextjs' },
  { id: 'cwecw', name: 'Graphql' },
  { id: 'cwecwe', name: 'Webpack' },
  { id: 'cwegwe', name: 'Ruby on Rails (basics)' },
  { id: 'cwevwe', name: 'Git' },
  { id: 'vewvwe', name: 'Sketch' },
];
